#! /bin/sh

### BEGIN INIT INFO
# Provides:          aptly-api
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO 

. /lib/lsb/init-functions

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=aptly-api
DESC="Aptly API service"
PIDFILE=/var/run/${NAME}.pid
DAEMON=/usr/bin/aptly
DAEMON_USER=aptly

[ -f /etc/default/${NAME} ] && . /etc/default/${NAME}

set -e

case "$1" in
    start)
        log_daemon_msg "Starting $DESC: "
        start-stop-daemon --start --chuid ${DAEMON_USER} -q -b -m --pidfile $PIDFILE --exec $DAEMON -- api serve -listen="$BIND"
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC: "
        start-stop-daemon --stop --user ${DAEMON_USER} -q --oknodo --pidfile $PIDFILE
        log_end_msg $?
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
    *)
        echo "Usage: service $NAME {start|stop|restart|status}" >&2
        exit 1
        ;;
esac

exit 0
